### ISSUE TITLE
get error when run testcases  for sdk=node userInputs/samplecc-chan1-join1.json

### ISSUE THREAD

**Issue by CocoaWang** [dongmingh/v1performance#1]
error: [Orderer.js]: sendDeliver - rejecting - status:FORBIDDEN
error: [Chain.js]: joinChannel - Failed Proposal. Error: Error: Invalid results returned ::FORBIDDEN
    at ClientDuplexStream.<anonymous> (/home/swangbj/gopath/src/github.com/hyperledger/fabric-sdk-node/node_modules/fabric-client/lib/Orderer.js:197:22)
    at emitOne (events.js:96:13)
    at ClientDuplexStream.emit (events.js:188:7)
    at readableAddChunk (_stream_readable.js:176:18)
    at ClientDuplexStream.Readable.push (_stream_readable.js:134:10)
    at readCallback (/home/swangbj/gopath/src/github.com/hyperledger/fabric-sdk-node/node_modules/grpc/src/node/src/client.js:245:14)
Error: Invalid results returned ::FORBIDDEN
    at ClientDuplexStream.<anonymous> (/home/swangbj/gopath/src/github.com/hyperledger/fabric-sdk-node/node_modules/fabric-client/lib/Orderer.js:197:22)
    at emitOne (events.js:96:13)
    at ClientDuplexStream.emit (events.js:188:7)
    at readableAddChunk (_stream_readable.js:176:18)
    at ClientDuplexStream.Readable.push (_stream_readable.js:134:10)
    at readCallback (/home/swangbj/gopath/src/github.com/hyperledger/fabric-sdk-node/node_modules/grpc/src/node/src/client.js:245:14)

**Comment by dongmingh** [comment]
which commit level do you see this?

**Comment by dongmingh** [comment]
observed same issue with b3f11a513d355541f1069e0bfc6c5979cbc8ad19 and fixed in fcb92e1fba6df900d8148b6a659876821b9ad208

**Comment by CocoaWang** [comment]
fabric commit level : 9e40c3c0070303285b4249112c966969551d9056 
fabric-sdk-node  commit level : 45c2f389ef37f3eab64cfceace46b0157abb9d33 
fabric-ca commit level : 77dc0ce08853615e6876db81fb9384c4e9c31209 
v1Laucher and v1performace  use the latest

**Comment by CocoaWang** [comment]
@dongmingh  The workflow is  create channel \   join channel \  install .  Am I right? Thank you !

**Comment by CocoaWang** [comment]
@dongmingh   Hi ,I have fixed this problem by clean my tmp files.  
cd /tmp
rm -rf *

**Comment by dongmingh** [comment]
The sequence of workflow is create channel, join channel, install chaincode and instantiate chaincode.
If the keys are still in the /tmp/hfc-test-kvs*, then there will be errors as you observed.  It is needed to "rm -rf /tmp/hfc-test-kvs*" if the network is bring up.

**Comment by CocoaWang** [comment]
@dongmingh  Yes. Thanks for your help!

**Comment by dongmingh** [comment]
Is this issue resolved?  If yes, please close the issue. Thanks.

**Comment by dongmingh** [comment]
shall this be closed?

**Comment by CocoaWang** [comment]
sure.thanks

**Comment by dongmingh** [comment]
close the issue per response
