### ISSUE TITLE
Report Timed out problem when send transactions to network

### ISSUE THREAD

**Issue by z21921** [dongmingh/v1performance#16]
1. PTE level: commit a15e57fff263406b2a6fd9e1f9ee84fec9396fd0
2. Fabric level 1.0GA

Problems: 
I create/join/install/instaniate network. 
Then I use runCases-constant-i.zvm to send request.

PTE report following problems:

info: [PTE 0 main]: stderr: error: [Peer.js]: sendProposal - timed out after:45000

info: [PTE 0 main]: stderr: error: [Peer.js]: sendProposal - timed out after:45000
error: [client-utils.js]: sendPeersProposal - Promise is rejected: Error: REQUEST_TIMEOUT
    at Timeout._onTimeout (/root/gopath/src/github.com/hyperledger/fabric-sdk-node/node_modules/fabric-client/lib/Peer.js:100:19)
    at ontimeout (timers.js:365:14)
    at tryOnTimeout (timers.js:237:5)

**Comment by dongmingh** [comment]
What is your network configuration and which org were the chaincode installed and instantiated?
If the chaincode is not instantiated on all org, it will take some time for all peers to synch-up.  Before synch-up, the transaction will timeout with the message you reported.
If this is the case, run a short query against all org until you see all transaction go thru, then you can run your test cases.
